import Head from 'next/head'
import PKL from '../components/PKL';
import styles from '../styles/Home.module.css'

export default function Home() {
  return (
    <div>
      <Head>
        <title>PKLUI</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main>
        <h2>
          PKL-UI
        </h2>

        <PKL title="Sains" />
      </main>

      <footer>
          Copyright
      </footer>
    </div>
  );
}